name: Build ESP32 Application

on:
  workflow_dispatch:
    inputs:
      board:
        description: 'Board to build for (all or specific board name)'
        required: true
        default: 'all'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [esp-box-3, esp-box, m5stack_core_s3, esp32_p4_function_ev_board]
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: esp-idf build and merge binaries
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: latest
          path: '.'
          command: idf.py @boards/${{ matrix.board }}.cfg build &&
            cd build.${{ matrix.board }} &&
            esptool.py --chip ${{ matrix.board }} merge_bin --output combined-open-tyrian-${{ matrix.board }}.bin --flash_mode dio --flash_freq 80m --flash_size 16MB \
                0x2000 bootloader/bootloader.bin \
                0x8000 partition_table/partition-table.bin \
                0x10000 esp32-open-tyrian.bin \
                0x310000 storage.bin

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build.${{ matrix.board }}
          path: build.${{ matrix.board }}/combined-open-tyrian-${{ matrix.board }}.bin
