name: Build ESP32 Application

on:
  workflow_dispatch:
    inputs:
      board:
        description: 'Board to build for (all or specific board name)'
        required: true
        default: 'all'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [esp-box-3, esp-box, m5stack-core-s3, esp32-p4-function-ev-board]
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install ESP-IDF dependencies
        run: |
          python -m pip install --upgrade pip
          pip install espressif-python-idf

      - name: Install esptool.py
        run: |
          pip install esptool

      - name: Set Configuration File
        run: |
          echo "BOARD_CONFIG=$(case ${{ matrix.board }} in
            esp-box-3) echo 'esp-box-3.cfg';;
            esp-box) echo 'esp-box.cfg';;
            m5stack-core-s3) echo 'm5stack_core_s3.cfg';;
            esp32-p4-function-ev-board) echo 'esp32_p4_function_ev_board.cfg';;
            *) echo 'Unknown board'; exit 1;;
          esac)" >> $GITHUB_ENV

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: v5.3
          target: ${{ matrix.board }}
          path: '.'
          command: idf.py -B build.${{ matrix.board }} @boards/${{ env.BOARD_CONFIG }} build

      - name: Merge Binaries into Single Image
        run: |
          cd build.${{ matrix.board }}
          esptool.py --chip ${{ matrix.board }} merge_bin --output combined-open-tyrian-${{ matrix.board }}.bin --flash_mode dio --flash_freq 80m --flash_size 16MB \
            0x2000 bootloader/bootloader.bin \
            0x8000 partition_table/partition-table.bin \
            0x10000 esp32-open-tyrian.bin \
            0x310000 storage.bin

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build.${{ matrix.board }}
          path: build.${{ matrix.board }}/combined-open-tyrian-${{ matrix.board }}.bin
