name: Create GitHub Release

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the GitHub Release'
        required: true
        default: 'v1.0.0'
      release_tag:
        description: 'Tag for the GitHub Release'
        required: true
        default: 'v1.0.0'
      prefix:
        description: 'Prefix for binary name'
        required: true
        default: 'opentyrian'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Check if Release Exists
        id: check_release
        run: |
          set +e
          gh release view ${{ github.event.inputs.release_tag }} > /dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "Release already exists."
            echo "release_exists=true" >> $GITHUB_ENV
          else
            echo "Release does not exist."
            echo "release_exists=false" >> $GITHUB_ENV
          fi
          set -e

      - name: Generate Flashing Instructions
        run: |
          cat > /tmp/release_notes.md <<EOF
          # OpenTyrian ${{ github.event.inputs.release_tag }}

          ## Installation Instructions

          1. Download the appropriate zip file for your board
          2. Extract the zip file
          3. Run the flashing script for your platform:
             - Linux/macOS: `./flash.sh`
             - Windows (Command Prompt): `flash.bat`
             - Windows (PowerShell): `flash.ps1`

          ## Manual Flashing

          If you prefer to flash manually using espflash:
          ```
          espflash flash --bootloader bootloader-[board].bin --partition-table partition-table-[board].bin opentyrian.bin
          ```

          Or using esptool.py:
          ```
          esptool.py write_flash 0x0 bootloader-[board].bin 0x8000 partition-table-[board].bin 0x10000 opentyrian.bin
          ```

          ## Available Boards
          - m5stack_core_s3
          - esp32_p4_function_ev_board
          EOF

      - name: Create Release
        if: env.release_exists == 'false'
        run: |
          gh release create ${{ github.event.inputs.release_tag }} --title "${{ github.event.inputs.release_name }}" --prerelease --notes-file /tmp/release_notes.md

      - name: Download Build Artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          path: artifacts

      - name: List Downloaded Files
        run: |
          echo "Listing all files in the artifacts directory:"
          find artifacts -type f

      - name: Upload Package Assets to Release
        run: |
          # Upload all zip packages to the release
          for file in $(find artifacts -type f -name "*.zip"); do
            # Upload the zip package directly
            gh release upload "${{ github.event.inputs.release_tag }}" "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
