name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the release'
        required: true
      board:
        description: 'Board to release'
        required: true
        default: 'all'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_name }}
          release_name: ${{ github.event.inputs.release_name }}
          body: 'Release for ${{ github.event.inputs.release_name }}'
          draft: true
          prerelease: false

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.board }}-build
          path: build/

      - name: Upload assets to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/
          asset_name: ${{ matrix.board }}-artifacts.zip
          asset_content_type: application/zip
