name: Test ESP32 Application

on:
  workflow_run:
    workflows: ["Build ESP32 Application"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [esp-box-3, esp-box, m5stack_core_s3, esp32_p4_function_ev_board]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build.${{ matrix.board }}
          path: build/

      - name: Setup Wokwi CLI
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: .
          timeout: 30000
          expect_text: 'OpenTyrian initialization...'
          fail_text: 'Error'
          serial_log_file: 'wokwi-logs-${{ matrix.board }}.txt'

      - name: Upload Wokwi Logs
        uses: actions/upload-artifact@v4
        with:
          name: wokwi-logs-${{ matrix.board }}
          path: wokwi-logs-${{ matrix.board }}.txt
